# coding: utf-8

"""
    Power Query

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.default_api import DefaultApi  # noqa: E501
from swagger_client.rest import ApiException


class TestDefaultApi(unittest.TestCase):
    """DefaultApi unit test stubs"""

    def setUp(self):
        self.api = DefaultApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_db_delete(self):
        """Test case for db_delete

        """
        pass

    def test_db_get(self):
        """Test case for db_get

        """
        pass

    def test_db_post(self):
        """Test case for db_post

        """
        pass

    def test_db_put(self):
        """Test case for db_put

        """
        pass

    def test_table_get(self):
        """Test case for table_get

        """
        pass

    def test_table_put(self):
        """Test case for table_put

        """
        pass


if __name__ == '__main__':
    unittest.main()
